name: ofc_app
description: Minimal Flutter app wired to ofc_app_core.
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ofc_app_core:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon-1024.png
  adaptive_icon_background: "#FFE082"                 # 明るい単色背景
  adaptive_icon_foreground: assets/icon/ic_adaptive_foreground.png
  remove_alpha_ios: true
