name: Build Check

on:
  push:
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: 'stable'
          cache: true

      - name: Analyze
        run: make app-analyze

      - name: Build Web
        run: make app-build-web

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        working-directory: app
        run: flutter pub get

      - name: Analyze
        run: make app-analyze

      - name: Build iOS (no signing)
        working-directory: app
        run: flutter build ios --release --no-codesign
