name: Build Check

on:
  push:
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd app
          flutter pub get

      - name: Analyze code
        run: |
          cd app
          flutter analyze

      - name: Build Web
        run: |
          cd app
          flutter build web --release

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd app
          flutter pub get

      - name: Analyze code
        run: |
          cd app
          flutter analyze

      - name: Build iOS (no signing)
        run: |
          cd app
          flutter build ios --release --no-codesign
