name: Build Check

on:
  push:
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Flutter
        uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # v2.22.0
        with:
          channel: 'stable'
          cache: true

      - name: Analyze
        run: make app-analyze

      - name: Build Web
        run: make app-build-web

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Flutter
        uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # v2.22.0
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        working-directory: app
        run: flutter pub get

      - name: Analyze
        run: make app-analyze

      - name: Build iOS (no signing)
        working-directory: app
        run: flutter build ios --release --no-codesign
